# Generated by Django 2.2.1 on 2019-08-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
