# Generated by Django 2.2.1 on 2019-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0003_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='switch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_number',
            field=models.IntegerField(default=0),
        ),
    ]
