# Generated by Django 2.2.1 on 2019-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0004_auto_20190814_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpid', models.IntegerField(default=0)),
                ('mfr_desc', models.CharField(default='', max_length=50)),
                ('hw_desc', models.CharField(default='', max_length=50)),
                ('sw_desc', models.CharField(default='', max_length=50)),
                ('serial_num', models.CharField(default='', max_length=50)),
                ('dp_desc', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
