# Generated by Django 2.2.1 on 2019-08-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0005_switchhardware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchhardware',
            name='dpid',
        ),
    ]
