# Generated by Django 2.2.1 on 2019-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0009_portstats_dpid'),
    ]

    operations = [
        migrations.AddField(
            model_name='portstats',
            name='tx_dropped',
            field=models.IntegerField(default=0),
        ),
    ]
