# Generated by Django 2.2.1 on 2019-08-16 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0010_portstats_tx_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='descstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 16, 10, 12, 16, 395353, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descstats',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flowaggregatestats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 16, 10, 12, 30, 502944, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowaggregatestats',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flowstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 16, 10, 12, 35, 415640, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flowstats',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portstats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 16, 10, 12, 43, 70120, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portstats',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablestats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablestats',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
