# Generated by Django 2.2.1 on 2019-08-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0012_portstats_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portstats',
            name='port',
        ),
    ]
