# Generated by Django 2.2.1 on 2019-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0013_remove_portstats_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowAggregateDiffStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpid', models.IntegerField(default=-1)),
                ('packet_count', models.IntegerField(default=-1)),
                ('byte_count', models.IntegerField(default=-1)),
                ('flow_count', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortDiffStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpid', models.IntegerField(default=-1)),
                ('tx_dropped', models.IntegerField(default=-1)),
                ('port_number', models.IntegerField(default=-1)),
                ('rx_packets', models.IntegerField(default=-1)),
                ('rx_crc_err', models.IntegerField(default=-1)),
                ('tx_bytes', models.IntegerField(default=-1)),
                ('rx_dropped', models.IntegerField(default=-1)),
                ('port_no', models.CharField(default='No Data Yet', max_length=50)),
                ('rx_over_err', models.IntegerField(default=-1)),
                ('rx_frame_err', models.IntegerField(default=-1)),
                ('rx_bytes', models.IntegerField(default=-1)),
                ('tx_errors', models.IntegerField(default=-1)),
                ('duration_nsec', models.IntegerField(default=-1)),
                ('collisions', models.IntegerField(default=-1)),
                ('duration_sec', models.IntegerField(default=-1)),
                ('rx_errors', models.IntegerField(default=-1)),
                ('tx_packets', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='descstats',
            name='dp_desc',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='descstats',
            name='hw_desc',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='descstats',
            name='mfr_desc',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='descstats',
            name='serial_num',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='descstats',
            name='sw_desc',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowaggregatestats',
            name='byte_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowaggregatestats',
            name='dpid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowaggregatestats',
            name='flow_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowaggregatestats',
            name='packet_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='actions',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='byte_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='cookie',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='dpid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='duration_nsec',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='duration_sec',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='flags',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='hard_timeout',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='idle_timeout',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='match',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='packet_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='priority',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='flowstats',
            name='table_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='collisions',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='dpid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='duration_nsec',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='duration_sec',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='port_no',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='port_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_bytes',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_crc_err',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_dropped',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_errors',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_frame_err',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_over_err',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='rx_packets',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='tx_bytes',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='tx_dropped',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='tx_errors',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='portstats',
            name='tx_packets',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tablestats',
            name='active_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tablestats',
            name='dpid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tablestats',
            name='lookup_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tablestats',
            name='matched_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tablestats',
            name='table_id',
            field=models.IntegerField(default=-1),
        ),
    ]
