# Generated by Django 2.2.1 on 2019-08-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0015_auto_20190825_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='portdiffstats',
            name='latest_port_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='sdn_communication.PortStats'),
        ),
        migrations.AddField(
            model_name='portdiffstats',
            name='penultimate_port_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penultimate', to='sdn_communication.PortStats'),
        ),
    ]
