# Generated by Django 2.2.1 on 2019-08-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0016_auto_20190825_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portdiffstats',
            name='port_number',
        ),
        migrations.AlterField(
            model_name='flowaggregatediffstats',
            name='latest_flow_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='latest_flow', to='sdn_communication.FlowAggregateStats'),
        ),
        migrations.AlterField(
            model_name='flowaggregatediffstats',
            name='penultimate_flow_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penultimate_flow', to='sdn_communication.FlowAggregateStats'),
        ),
        migrations.AlterField(
            model_name='portdiffstats',
            name='latest_port_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='latest_port', to='sdn_communication.PortStats'),
        ),
        migrations.AlterField(
            model_name='portdiffstats',
            name='penultimate_port_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='penultimate_port', to='sdn_communication.PortStats'),
        ),
    ]
