# Generated by Django 2.2.1 on 2019-08-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0017_auto_20190825_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portstats',
            name='port_number',
        ),
    ]
