# Generated by Django 2.2.1 on 2019-09-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0018_remove_portstats_port_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowaggregatediffstats',
            name='time_difference',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_number',
            field=models.IntegerField(default=-1),
        ),
    ]
