# Generated by Django 2.2.1 on 2019-09-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0021_auto_20190916_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowaggregatediffstats',
            old_name='interval_diff',
            new_name='time_interval',
        ),
        migrations.RenameField(
            model_name='portdiffstats',
            old_name='interval_diff',
            new_name='time_interval',
        ),
    ]
