# Generated by Django 2.2.1 on 2019-09-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0023_attacknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacknotification',
            name='attack_true',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='attacknotification',
            name='percentage',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='attacknotification',
            name='threshold',
            field=models.FloatField(default=-1),
        ),
    ]
