# Generated by Django 2.2.1 on 2019-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0024_auto_20190917_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controllerIP', models.CharField(default='0.0.0.0', max_length=50)),
            ],
        ),
    ]
