# Generated by Django 2.2.1 on 2019-09-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0025_configurationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmodel',
            name='ml_threshold',
            field=models.FloatField(default=-1),
        ),
    ]
