# Generated by Django 2.2.1 on 2019-09-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0026_configurationmodel_ml_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmodel',
            name='flow_aggregate_difference_threshold',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='configurationmodel',
            name='flow_aggregate_threshold',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='configurationmodel',
            name='port_diff_threshold',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='configurationmodel',
            name='port_threshold',
            field=models.IntegerField(default=-1),
        ),
    ]
