# Generated by Django 2.2.1 on 2019-09-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0026_configurationmodel_ml_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='switch_number',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
