# Generated by Django 2.2.1 on 2019-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0028_attacknotification_attack_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacknotification',
            name='port_no',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
    ]
