# Generated by Django 2.2.1 on 2019-10-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0029_attacknotification_port_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacknotification',
            name='attack_value',
            field=models.FloatField(default=-1),
        ),
    ]
