# Generated by Django 2.2.1 on 2019-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0032_auto_20191021_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowaggregatestats',
            name='byte_count',
            field=models.CharField(default='No Data Yet', max_length=50),
        ),
    ]
