# Generated by Django 2.2.1 on 2019-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdn_communication', '0033_auto_20191021_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowaggregatestats',
            name='byte_count',
            field=models.BigIntegerField(default=-1),
        ),
    ]
